"use server";

import { getUser, hasPermission } from "@/lib/auth";
import { ActivityLogService, type ActivityLogFilters } from "@/features/activity";
import { ActivityService } from "@/services/activity.service";
import type { ModuleReport } from "@/features/reports";

/**
 * Historia 16.11 — builds the audit log report for PDF export. The PDF
 * itself is rendered client-side (lib/export-pdf) with the shared report
 * shape; the export is audited here server-side.
 */
export async function getActivityExportReport(
  filters: ActivityLogFilters,
): Promise<{ report?: ModuleReport; error?: string }> {
  try {
    const user = await getUser();
    if (!user) return { error: "Unauthenticated." };
    if (!hasPermission(user, "users.read")) return { error: "You cannot export the activity log." };

    const logs = await ActivityLogService.listForExport(filters);

    await ActivityService.logAccessOnce({
      user_id: user.id,
      action: "exported_activity",
      entity: "ActivityLog",
      new_value: { format: "pdf", count: logs.length },
    });

    const report: ModuleReport = {
      id: "activity",
      title: "Activity Log",
      kpis: [
        { label: "Exported records", value: logs.length },
        { label: "Generated by", value: `${user.first_name} ${user.last_name}` },
      ],
      table: {
        columns: ["Date", "User", "Action", "Entity", "Old Value", "New Value"],
        rows: logs.slice(0, 400).map((log) => [
          new Date(log.created_at).toLocaleString(),
          [log.user_first_name, log.user_last_name].filter(Boolean).join(" ") || "System",
          log.action,
          log.entity,
          log.old_value ?? "—",
          log.new_value ?? "—",
        ]),
      },
      generatedAt: new Date().toISOString(),
    };

    return { report };
  } catch (err) {
    return { error: err instanceof Error ? err.message : "Failed to export activity log." };
  }
}
